apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- demoCA
- cert-manager
- truststore-keystore
- cass-operator
- Reaper

images:
- name: thelastpickle/cassandra-reaper
  newTag: 2.3.1