apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cass-operator
generatorOptions:
 disableNameSuffixHash: true
secretGenerator:
- name: jks-password
  files:
  - keystore-pass
resources:
- Issuer.yaml
- Cassandra-Certificate.yaml
- Reaper-Certificate.yaml