apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cass-operator
generatorOptions:
 disableNameSuffixHash: true
resources:
- Reaper-deployment.yaml
configMapGenerator:
- name: cqlsh-config
  files:
  - cqlshrc
